image:
  name: $template_default_taito_image
  username: $template_default_taito_image_username
  password: $template_default_taito_image_password
  email: $template_default_taito_image_email
options:
  docker: true
  max-time: 60
definitions:
  services:
    docker:
      memory: 3072

pipelines:
  branches:
    # TODO: support for feature/* (cancel build if not included in taito_environments)
    '{dev,test,stag,canary,master}':
    # Prepare build
    - step:
        script:
          - export taito_mode=ci
          - taito build prepare:$BITBUCKET_BRANCH
        artifacts:
          - taitoflag_version
          - taitoflag_images_exist
    # Prepare artifacts in parallel
    - parallel:
      - step: # app prepare
          script:
            - export taito_mode=ci
            - taito artifact prepare:app:$BITBUCKET_BRANCH $BITBUCKET_COMMIT true
          artifacts:
            # TODO: define build artifact here
    # Deploy the changes to target environment
    - step:
        script:
          - export taito_mode=ci
          - taito deployment deploy:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
        # TODO: revert deployment on fail
        # after-script:
        #   - [ $BITBUCKET_EXIT_CODE != 0 ] && taito deployment revert:$BITBUCKET_BRANCH $BITBUCKET_COMMIT || :
        #   - [ $BITBUCKET_EXIT_CODE != 0 ] && taito db revert:$BITBUCKET_BRANCH $BITBUCKET_COMMIT || :
    # Test and verify deployment
    - step:
        script:
          - export taito_mode=ci
          - "taito -v artifact load: tester"
          - taito deployment wait:$BITBUCKET_BRANCH
          - taito test:$BITBUCKET_BRANCH
          - taito deployment verify:$BITBUCKET_BRANCH
        # # TODO: revert deployment on fail
        # after-script:
        #   - [ $BITBUCKET_EXIT_CODE != 0 ] && taito deployment revert:$BITBUCKET_BRANCH $BITBUCKET_COMMIT || :
        #   - [ $BITBUCKET_EXIT_CODE != 0 ] && taito db revert:$BITBUCKET_BRANCH $BITBUCKET_COMMIT || :
    # Release artifacts (optional)
    - parallel:
      - step: # app release
          script:
            - export taito_mode=ci
            - taito artifact release:app:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
    # Release build
    - step:
        script:
          - export taito_mode=ci
          - taito build release:$BITBUCKET_BRANCH
